services:
  logreq-python:
    profiles:
      - python
    build:
      context: ./src/python
      dockerfile: Dockerfile.python
    container_name: logreq-python
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8081:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
      - TIMEZONE=${TIMEZONE:-}
    env_file:
      - path: .env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  logreq-go:
    profiles:
      - go
      - golang
    build:
      context: ./src/go
      dockerfile: Dockerfile.golang
    container_name: logreq-go
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8081:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
      - TIMEZONE=${TIMEZONE:-}
    env_file:
      - path: .env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  logreq-js:
    profiles:
      - js
      - javascript
    build:
      context: ./src/js
      dockerfile: Dockerfile.javascript
    container_name: logreq-js
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8081:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
      - TIMEZONE=${TIMEZONE:-}
    env_file:
      - path: .env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped

