services:
  logreq-python:
    build:
      context: ./src/python
      dockerfile: Dockerfile.python
    container_name: logreq-python
    ports:
      - "8081:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
    env_file:
      - path: ./src/python/.env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  logreq-go:
    build:
      context: ./src/go
      dockerfile: Dockerfile.golang
    container_name: logreq-go
    ports:
      - "8082:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
    env_file:
      - path: ./src/go/.env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  logreq-js:
    build:
      context: ./src/js
      dockerfile: Dockerfile.javascript
    container_name: logreq-js
    ports:
      - "8083:8081"
    environment:
      - PROXY_TARGET=${PROXY_TARGET:-}
    env_file:
      - path: ./src/js/.env
        required: false
    volumes:
      - ./logs:/logs
    restart: unless-stopped
